import {test,expect} from '@playwright/test';
const text='ข้อความเกริ่นนำ\n'.repeat(45)+'หน้าที่ของบุคลากร\n'+'ข้อความระหว่างจุดที่ค้น\n'.repeat(35)+'หน้าที่ตามกฎหมาย\nหน้าที่และอำนาจ <script>window.injected=true</script>';
const row={id:'ocr-test',title:'ประกาศแต่งตั้ง บุคลากรทดสอบ',date:'2026-09-01',text,issuer:'หน่วยงานทดสอบ',volume:'1',part:'1',pdf:null,group:'appointments',sub:'บุคลากรอื่น ๆ'};
async function setup(page){
 await page.clock.setFixedTime(new Date('2026-09-24'));
 await page.route('**/data/*.json',route=>route.fulfill({json:route.request().url().includes('manifest.json')?{revision:'test',source:'https://huggingface.co',syncedAt:new Date().toISOString(),months:[{month:'2026-09'}]}:{revision:'test',complete:true,scanned:2,rows:[row,{...row,id:'no-text',title:'ประกาศแต่งตั้ง ไม่มีข้อความ OCR',text:''}]}}));
 await page.goto('/',{waitUntil:'domcontentloaded'});
 await expect(page.locator('.document-title')).toHaveCount(2);
}
for(const width of [390,1280])test(`OCR expansion, font controls, highlights and match navigation at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});await setup(page);
 await page.getByLabel('คำค้นหา',{exact:true}).fill('หน้าที่');
 await page.locator('.search-main').getByRole('button',{name:'ค้นหาประกาศ'}).click();
 await page.locator('.document-title').first().click();
 const dialog=page.getByRole('dialog'),reader=page.getByRole('region',{name:'ข้อความ OCR',exact:true});
 await expect(page.getByLabel('ค้นหาในข้อความ OCR')).toHaveValue('หน้าที่');
 await expect(reader.locator('mark')).toHaveCount(3);
 await expect(dialog.getByRole('status',{name:'ผลการค้นหาใน OCR'})).toHaveText('1 / 3 จุด');
 await expect(reader.locator('[aria-current="true"]')).toHaveAttribute('data-match','0');
 await expect.poll(()=>reader.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
 await page.getByRole('button',{name:'คำที่พบถัดไป'}).click();
 await expect(dialog.getByRole('status',{name:'ผลการค้นหาใน OCR'})).toHaveText('2 / 3 จุด');
 await page.getByLabel('ค้นหาในข้อความ OCR').press('Enter');
 await expect(dialog.getByRole('status',{name:'ผลการค้นหาใน OCR'})).toHaveText('3 / 3 จุด');
 await page.getByLabel('ค้นหาในข้อความ OCR').press('Shift+Enter');
 await expect(dialog.getByRole('status',{name:'ผลการค้นหาใน OCR'})).toHaveText('2 / 3 จุด');
 const before=await reader.boundingBox();
 await page.getByRole('button',{name:'ขยายพื้นที่อ่าน',exact:true}).click();
 await expect(dialog).toHaveClass(/modal-reader-expanded/);
 const after=await reader.boundingBox();expect(after.height).toBeGreaterThan(before.height);
 await page.getByRole('button',{name:'เพิ่มขนาดตัวอักษร OCR'}).click();
 await expect(reader).toHaveCSS('font-size','20px');
 await page.getByLabel('แบบอักษร OCR',{exact:true}).selectOption('serif');
 await expect(reader).toHaveCSS('font-family',/Noto Serif Thai/);
 for(let i=0;i<8;i++)await page.getByRole('button',{name:'เพิ่มขนาดตัวอักษร OCR'}).click();
 await expect(reader).toHaveCSS('font-size','36px');
 await expect(page.getByRole('button',{name:'เพิ่มขนาดตัวอักษร OCR'})).toBeDisabled();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.getByLabel('ค้นหาในข้อความ OCR').fill('ไม่พบคำนี้');
 await expect(dialog.getByRole('status',{name:'ผลการค้นหาใน OCR'})).toHaveText('ไม่พบคำใน OCR');
 await expect(reader.locator('mark')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'คำที่พบถัดไป'})).toBeDisabled();
 expect(await page.evaluate(()=>window.injected)).toBeUndefined();
 await page.getByRole('button',{name:'ย่อพื้นที่อ่าน',exact:true}).click();
 await expect(dialog).not.toHaveClass(/modal-reader-expanded/);
 await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();
 await page.locator('.document-title').first().click();
 await expect(reader).toHaveCSS('font-size','36px');
 await expect(reader).toHaveCSS('font-family',/Noto Serif Thai/);
 await expect(page.getByLabel('ค้นหาในข้อความ OCR')).toHaveValue('หน้าที่');
 await page.getByRole('button',{name:'คืนค่า',exact:true}).click();
 await expect(reader).toHaveCSS('font-size','18px');
 await page.getByRole('button',{name:'ลดขนาดตัวอักษร OCR'}).click();
 await expect(reader).toHaveCSS('font-size','16px');
});
test('empty OCR remains readable and does not show fake matches',async({page})=>{
 await setup(page);await page.locator('.document-title').nth(1).click();
 await expect(page.getByLabel('ค้นหาในข้อความ OCR')).toBeDisabled();
 await expect(page.getByRole('region',{name:'ข้อความ OCR',exact:true})).toContainText('ยังไม่มีข้อความ OCR');
 await expect(page.getByRole('button',{name:'คำที่พบถัดไป'})).toBeDisabled();
});
