import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,ArrowUpRight,ArrowRight,BookOpen,Sun,Moon,RefreshCw,Database,ChevronDown,SlidersHorizontal,X,Check,FileText,CalendarDays,Bookmark,Users,ShieldCheck,LayoutGrid,List,ExternalLink,Info,LoaderCircle,CheckCircle2,AlertCircle,ChevronLeft,ChevronRight,Library,Clock3,Download} from 'lucide-react';
import {fetchMonth} from './dataset';
import {loadPublishedData} from './static-data';
import Pagination from './Pagination';
const STATIC=import.meta.env.VITE_STATIC_DATA==='true';
import {groups,filterRows,DATASET} from './search';
import './style.css';
const defaults={q:'',group:'all',sub:'',from:'',to:'',scope:'all',match:'all',exclude:'',agency:'',ocr:false,sort:'newest'};
const dateTH=d=>d?new Date(d+'T00:00:00').toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}):'ไม่ระบุวันที่';
function Reader(){return <div className="reader-scene" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="spark s1">✧</span><span className="spark s2">✦</span><span className="spark s3">✧</span><div className="floating-note"><Check size={13}/> เจอเรื่องที่ใช่แล้ว!</div><svg className="reader" viewBox="0 0 300 260" fill="none"><ellipse cx="153" cy="237" rx="108" ry="13" fill="#dfdfc9"/><path d="M101 178C70 174 57 214 81 225L151 229L190 223C221 217 207 184 183 177" fill="#a0a583" stroke="#333b2e" strokeWidth="3"/><path d="M130 208L96 225M171 206L197 223" stroke="#333b2e" strokeWidth="3"/><path d="M116 116C88 127 83 160 94 188C122 205 170 203 195 186C203 146 183 123 165 117" fill="#805aaa" stroke="#333b2e" strokeWidth="3"/><path d="M130 103L129 123Q144 139 158 121L158 103" fill="#efbd9a" stroke="#333b2e" strokeWidth="3"/><ellipse cx="144" cy="83" rx="35" ry="39" fill="#f4c7a6" stroke="#333b2e" strokeWidth="3"/><path d="M109 79C97 69 103 42 123 37C135 21 168 31 179 50C187 64 179 78 178 79L166 63C149 73 138 62 132 56C128 74 116 74 109 79Z" fill="#343c30"/><circle cx="132" cy="83" r="3" fill="#333b2e"/><circle cx="158" cy="83" r="3" fill="#333b2e"/><path d="M139 99Q145 105 152 98" stroke="#333b2e" strokeWidth="2.5" strokeLinecap="round"/><path d="M82 145Q111 136 145 153Q175 136 208 143L195 194Q170 188 145 207Q120 188 94 195Z" fill="#fbf8e9" stroke="#333b2e" strokeWidth="3"/><path d="M145 154V204" stroke="#333b2e" strokeWidth="2"/><path className="book-lines" d="M100 156L131 164M103 166L131 174M161 164L192 155M161 174L189 166M161 183L183 177" stroke="#b5ba9b" strokeWidth="3" strokeLinecap="round"/><ellipse cx="95" cy="174" rx="10" ry="14" transform="rotate(-25 95 174)" fill="#f4c7a6" stroke="#333b2e" strokeWidth="2.5"/><ellipse cx="195" cy="173" rx="10" ry="14" transform="rotate(25 195 173)" fill="#f4c7a6" stroke="#333b2e" strokeWidth="2.5"/><path d="M72 213L62 224Q67 236 91 228M204 213L221 226Q215 237 191 228" fill="#3c4434"/></svg><div className="floating-search"><Search size={20}/></div></div>}
function App(){
 const [dark,setDark]=useState(()=>localStorage.getItem('theme')==='dark');
 const [allMonths,setAllMonths]=useState(STATIC);
 const [selectedYear,setSelectedYear]=useState(String(new Date().getFullYear()));
 const [pageSize,setPageSize]=useState(20);
 const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[dataInfo,setDataInfo]=useState(null);
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(false),[connection,setConnection]=useState(null),[connectionError,setConnectionError]=useState(false),[statusOpen,setStatusOpen]=useState(false);
 const [f,setF]=useState(defaults),[input,setInput]=useState(''),[advanced,setAdvanced]=useState(false),[toasts,setToasts]=useState([]),[selected,setSelected]=useState(null),[page,setPage]=useState(1),[view,setView]=useState('list'),[savedOnly,setSavedOnly]=useState(false),[saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem('saved')||'[]')}catch{return []}}),[help,setHelp]=useState(false);
 const request=useRef(0);
 const notify=(text,type='success')=>{const id=Date.now()+Math.random();setToasts(t=>[...t.slice(-2),{id,text,type}]);setTimeout(()=>setToasts(t=>t.filter(x=>x.id!==id)),5500)};
 const change=(key,value)=>{setF(p=>({...p,[key]:value,...(key==='group'?{sub:''}:{})}));setPage(1)};
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('theme',dark?'dark':'light')},[dark]);
 useEffect(()=>{localStorage.setItem('saved',JSON.stringify(saved))},[saved]);
 useEffect(()=>{const handler=e=>{if(e.key==='Escape'){setSelected(null);setHelp(false);setStatusOpen(false)}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[]);
 useEffect(()=>{connect('',false)},[]);
 async function connect(_query='',refresh=true,targetMonth=month,useAll=allMonths,year=selectedYear,range){
 const id=++request.current;setLoading(true);notify('กำลังโหลดข้อมูลจริงจากฐานราชกิจจานุเบกษา…','loading');
 const apply=data=>{if(id!==request.current)return;setRows(data.rows);setDataInfo(data);setConnection(data.connectedAt);setConnectionError(!!data.stale);setPage(1)};
 let fallback=null;
 try{
   if(STATIC){
     const data=await loadPublishedData(import.meta.env.BASE_URL,targetMonth,{all:useAll,year,range});
     if(id!==request.current)return;
     apply(data);
     notify(`โหลดข้อมูลจริง ${data.rows.length} ประกาศ • OCR ${data.rows.filter(r=>r.text).length} ฉบับ${data.stale?' • ข้อมูลซิงก์เกิน 48 ชั่วโมง':''}`,data.stale?'error':'success');
     return;
   }

   try{
     const r=await fetch('/api/search?'+new URLSearchParams({month:targetMonth,refresh:refresh?'1':'0'}),{signal:AbortSignal.timeout(22000)});
     const data=await r.json();if(!r.ok)throw Error(data.error);
     fallback=data;
     if(data.stale&&dataInfo?.month===targetMonth&&dataInfo.complete){fallback={...dataInfo,rows,stale:true}}
     apply(fallback);
   }catch(e){/* The browser may reach the public dataset when the API host cannot. */}
   if(id!==request.current)return;
   if(!fallback||fallback.stale){
     try{const direct=await fetchMonth(targetMonth);if(id!==request.current)return;apply(direct);notify(`โหลดข้อมูลจริงสำเร็จ ${direct.rows.length} ประกาศ จาก ${direct.scanned} รายการในเดือน ${targetMonth}`);return}
     catch(e){if(id!==request.current)return;if(!fallback)throw e;}
   }
   if(fallback.stale)notify(`เชื่อมต่อสดไม่ได้ • แสดงสำเนาข้อมูลจริง ${fallback.rows.length} รายการ${fallback.complete?'':' (บางส่วน)'}`,'error');
   else notify(`พร้อมค้นข้อมูลจริง ${fallback.rows.length} ประกาศ ประจำเดือน ${targetMonth}`);
 }catch(e){if(id!==request.current)return;setConnectionError(true);notify((STATIC?e.message:'โหลดเดือนที่เลือกไม่สำเร็จ ข้อมูลเดิมยังคงอยู่ กรุณาลองใหม่'),'error')}
 finally{if(id===request.current)setLoading(false)}
 }
 async function loadOCR(query){
 if(STATIC){notify(`ค้นข้อความ OCR ที่นำเข้าแล้ว ${rows.filter(r=>r.text).length} ฉบับ (บางประกาศอาจไม่มี OCR)`);return}
 if(!query.trim()){notify('กรุณาระบุคำค้นสำหรับค้นข้อความ OCR','error');return}
 const id=++request.current;setLoading(true);notify('กำลังค้นข้อความ OCR จากฐานต้นทาง…','loading');
 try{
 const r=await fetch('/api/ocr-search?'+new URLSearchParams({q:query}),{signal:AbortSignal.timeout(25000)});
 const data=await r.json();if(!r.ok)throw Error(data.error);
 if(id!==request.current)return;const byId=new Map(data.rows.map(r=>[r.id,r]));
 setRows(previous=>previous.map(r=>{const o=byId.get(r.id)||data.rows.find(o=>o.id===r.pdfFile);if(!o?.text)return r;return {...r,text:o.text}}));
 notify('โหลด OCR แล้ว • ค้นเฉพาะข้อความที่จับคู่กับประกาศในเดือนที่แสดงได้');
 }catch(e){if(id!==request.current)return;notify('บริการ OCR ยังเชื่อมต่อไม่ได้ กรุณาเปิด PDF ต้นฉบับแทน','error')}
 finally{if(id===request.current)setLoading(false)}
 }
 function search(e){e?.preventDefault();if(f.from&&f.to&&f.from>f.to){notify('วันที่เริ่มต้นต้องไม่เกินวันที่สิ้นสุด','error');return}change('q',input);if(STATIC&&(f.from||f.to)){connect(input,true,month,true,selectedYear,{from:f.from,to:f.to})}else if(f.scope==='text')loadOCR(input);else notify('ค้นหาในข้อมูลจริงที่โหลดแล้ว')}
 function toggleSaved(r){setSaved(p=>p.includes(r.id)?p.filter(x=>x!==r.id):[...p,r.id]);notify(saved.includes(r.id)?'นำออกจากรายการที่บันทึกแล้ว':'บันทึกประกาศไว้ในเบราว์เซอร์แล้ว')}
 const filtered=filterRows(rows,f).filter(r=>!savedOnly||saved.includes(r.id));const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const safePage=Math.min(page,pages);const visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
 const filterCount=[f.sub,f.from,f.to,f.exclude,f.agency,f.ocr,f.scope!=='all',f.match!=='all'].filter(Boolean).length;
 const reset=()=>{setF(defaults);setInput('');setPage(1);setSavedOnly(false);notify('ล้างตัวกรองทั้งหมดแล้ว')};
 function highlight(text){const term=f.q.trim();if(!term)return text;const idx=text.toLowerCase().indexOf(term.toLowerCase());return idx<0?text:<>{text.slice(0,idx)}<mark>{text.slice(idx,idx+term.length)}</mark>{text.slice(idx+term.length)}</>}
 return <><div className="announcement"><span className="tiny-dot"/> กฎหมายใกล้ตัว เข้าถึงง่ายกว่าที่เคย <span className="announcement-divider">|</span> ข้อมูลเปิด เพื่อทุกคน <ArrowUpRight size={13}/></div>
 <header className="header"><a className="brand" href="#" onClick={e=>{e.preventDefault();reset()}}><span className="brand-icon"><Library size={24}/></span><span>ราชค้น<span className="brand-en">RATCHA SEARCH</span></span></a><nav><a className={!savedOnly?'nav-active':''} href="#results" onClick={()=>setSavedOnly(false)}>ค้นหาประกาศ</a><button className={savedOnly?'nav-active':''} onClick={()=>{setSavedOnly(!savedOnly);setPage(1);document.getElementById('results').scrollIntoView({behavior:'smooth'})}}>รายการที่บันทึก {saved.length>0&&<small>{saved.length}</small>}</button><button onClick={()=>setHelp(true)}>เกี่ยวกับข้อมูล <ArrowUpRight size={13}/></button></nav><div className="header-actions"><button className="icon-button theme-button" title={dark?'โหมดสว่าง':'โหมดมืด'} aria-label="สลับโหมดสี" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><div className="connection-wrap"><button className="connection-button" onClick={()=>setStatusOpen(!statusOpen)}><span className={'tiny-dot '+(connection&&!connectionError?'green':'amber')}/><span>{loading?'กำลังเชื่อมต่อ':connection&&!connectionError?(STATIC?'ข้อมูลจริง · Pages':'เชื่อมต่อแล้ว'):(dataInfo?'ข้อมูลจริง · สำเนา':'สถานะฐานข้อมูล')}</span><ChevronDown size={13}/></button>{statusOpen&&<div className="connection-popover"><strong><Database size={17}/> การเชื่อมต่อฐานข้อมูล</strong><p>{connectionError?(STATIC?'ข้อมูลอาจเก่า หรือโหลดไม่สำเร็จ โปรดตรวจเวลา sync':'เชื่อมต่อสดไม่ได้ • กำลังแสดงสำเนาข้อมูลจริง'):connection?'โหลดข้อมูลจริงสำเร็จ':'กำลังโหลดข้อมูลจริง'}</p><label>{STATIC?'GitHub Actions ซิงก์ต้นทางสำเร็จล่าสุด':'โหลดจากต้นทางสำเร็จล่าสุด'}</label><p>{connection?new Date(connection).toLocaleString('th-TH'):(dataInfo?.retrievedOn?`นำเข้าข้อมูลจริงเมื่อ ${dataInfo.retrievedOn} (ไม่ใช่การเชื่อมต่อสด)`:'ยังไม่มีข้อมูลวันเวลา')}</p>{dataInfo&&<p>เดือน {dataInfo.month} • {dataInfo.rows.length} ประกาศ • {dataInfo.complete?'ตรวจครบไฟล์รายเดือน':'สำเนาบางส่วน ไม่ครบเดือน'}</p>}<a href={dataInfo?.source||DATASET} target="_blank" rel="noreferrer">เปิดไฟล์ฐานข้อมูลต้นทาง <ExternalLink size={14}/></a><button className="primary small" disabled={loading} onClick={()=>connect(f.q)}><RefreshCw size={15} className={loading?'spin':''}/> รีเฟรชการเชื่อมต่อ</button></div>}</div></div></header>
 <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> ทุกประกาศสำคัญ อยู่ใกล้แค่ปลายนิ้ว</div><h1>ค้นประกาศที่ใช่<br/><span>เข้าใจได้ง่ายขึ้น.</span><svg viewBox="0 0 340 15"><path d="M3 10Q160 -2 332 7M25 14Q180 5 314 11" stroke="currentColor" strokeWidth="2" fill="none"/></svg></h1><p>ค้นหาประกาศแต่งตั้งบุคลากร และประกาศที่เกี่ยวข้องกับ ป.ป.ช.<br className="desktop"/> จากราชกิจจานุเบกษา ในที่เดียว ง่าย ชัดเจน และตรวจสอบได้</p><div className="hero-benefits"><span><CheckCircle2/> ค้นลึกถึงเนื้อหา</span><span><CheckCircle2/> กรองได้ตรงใจ</span><span><CheckCircle2/> อ้างอิงต้นฉบับ</span></div></div><Reader/><div className="hero-side-note">A LITTLE CLARITY,<br/> A LOT OF POSSIBILITY.</div></section>
 <section className="search-panel"><form onSubmit={search}><div className="search-main"><Search size={23}/><input value={input} onChange={e=>setInput(e.target.value)} placeholder="ค้นหาชื่อประกาศ บุคคล หน่วยงาน หรือคำในเนื้อหา…" aria-label="คำค้นหา"/>{input&&<button type="button" className="icon-button" aria-label="ล้างคำค้น" onClick={()=>{setInput('');change('q','')}}><X size={16}/></button>}<button className="primary" disabled={loading}>{loading?<LoaderCircle size={18} className="spin"/>:<Search size={17}/>} ค้นหาประกาศ <ArrowRight size={17}/></button></div><div className="search-bottom"><div className="scope-options"><span>ค้นหาใน</span>{[['all','ทั้งหมด'],['title','ชื่อประกาศ'],['text','เนื้อหาในไฟล์']].map(([key,label])=><label key={key}><input type="radio" name="scope" checked={f.scope===key} onChange={()=>change('scope',key)}/>{label}{key==='text'&&<span className="ocr-mini">OCR</span>}</label>)}</div><button type="button" className={'advanced-button '+(advanced?'active':'')} onClick={()=>setAdvanced(!advanced)}><SlidersHorizontal size={16}/> ค้นหาขั้นสูง {filterCount>0&&<b>{filterCount}</b>}<ChevronDown size={14} className={advanced?'rotate':''}/></button></div>{advanced&&<div className="advanced-fields"><label>เงื่อนไขคำค้น<select value={f.match} onChange={e=>change('match',e.target.value)}><option value="all">ตรงทุกคำ (AND)</option><option value="any">ตรงคำใดคำหนึ่ง (OR)</option><option value="exact">ตรงทั้งวลี</option></select></label><label>ไม่รวมคำ<input value={f.exclude} onChange={e=>change('exclude',e.target.value)} placeholder="คำที่ไม่ต้องการ (NOT)"/></label><label>หน่วยงาน<input value={f.agency} onChange={e=>change('agency',e.target.value)} placeholder="ระบุชื่อหน่วยงาน"/></label><label className="check-label"><input type="checkbox" checked={f.ocr} onChange={e=>change('ocr',e.target.checked)}/> เฉพาะที่มีข้อความ OCR</label><p><Info size={13}/> เงื่อนไขขั้นสูงใช้กับรายการที่โหลดแล้ว • การค้นเนื้อหาใช้ข้อความ OCR ไม่ใช่การอ่าน PDF แบบสด</p></div>}</form></section>
 <div className="suggestions"><span>ลองค้นหา</span>{['แต่งตั้งข้าราชการ','กรรมการผู้ทรงคุณวุฒิ','ป.ป.ช.'].map(t=><button key={t} onClick={()=>{setInput(t);change('q',t);if(f.scope==='text')loadOCR(t)}}>{t}<ArrowUpRight size={12}/></button>)}</div>
 <section className="workspace" id="results"><aside className="filters"><div className="filter-title"><h3><SlidersHorizontal size={17}/> ตัวกรองการค้นหา</h3><button onClick={reset}>ล้างค่า</button></div><div className="filter-section"><h4>หมวดหมู่ประกาศ</h4><button className={'category '+(f.group==='all'?'selected':'')} onClick={()=>change('group','all')}><span><LayoutGrid size={16}/> ประกาศทั้งหมด</span><small>{rows.length}</small></button>{[['appointments',Users,'ประกาศแต่งตั้งบุคลากร'],['nacc',ShieldCheck,'สำนักงาน & คณะกรรมการ ป.ป.ช.']].map(([key,Icon,label])=><React.Fragment key={key}><button className={'category '+(f.group===key?'selected':'')} onClick={()=>change('group',key)}><span><Icon size={16}/>{label}</span><ChevronDown size={13}/></button>{f.group===key&&<div className="subcategories">{groups[key].map(s=><label key={s}><input type="radio" name="sub" checked={f.sub===s} onClick={()=>change('sub',s)}/>{s}<small>{rows.filter(r=>r.sub===s).length}</small></label>)}{f.sub&&<button onClick={()=>change('sub','')}>ทุกประเภทย่อย</button>}</div>}</React.Fragment>)}</div><div className="filter-section"><h4><CalendarDays size={15}/> ช่วงวันที่ประกาศ</h4><label className="date-label">ตั้งแต่วันที่<input type="date" value={f.from} max={f.to||undefined} onChange={e=>change('from',e.target.value)}/></label><label className="date-label">ถึงวันที่<input type="date" value={f.to} min={f.from||undefined} onChange={e=>change('to',e.target.value)}/></label><div className="date-shortcuts"><button onClick={()=>{const end=new Date();const start=new Date();start.setDate(start.getDate()-30);setF(p=>({...p,from:start.toISOString().slice(0,10),to:end.toISOString().slice(0,10)}));setPage(1)}}>30 วันล่าสุด</button><button onClick={()=>{const y=new Date().getFullYear();setF(p=>({...p,from:y+'-01-01',to:y+'-12-31'}));setPage(1)}}>ปีนี้</button><button onClick={()=>{setF(p=>({...p,from:'',to:''}));setPage(1)}}>ทั้งหมด</button></div><p className="date-hint">เลือกวันที่ ค.ศ. • ผลลัพธ์แสดงปี พ.ศ. • กดค้นหาเพื่อโหลดช่วงวันที่ข้ามปี</p></div><div className="data-note"><div className="note-icon"><Database size={19}/><span className="tiny-dot"/></div><h4>ข้อมูลเปิด เข้าถึงได้ทุกคน</h4><p>อ้างอิงจาก Open Law Data Thailand<br/>ตรวจสอบเอกสารต้นฉบับได้เสมอ</p><a href={DATASET} target="_blank" rel="noreferrer">สำรวจฐานข้อมูล <ArrowUpRight size={14}/></a></div></aside>
 <div className="results"><div className="results-heading"><div><div className="section-eyebrow">EXPLORE THE GAZETTE</div><h2>{savedOnly?'ประกาศที่บันทึกไว้':'ประกาศที่คุณกำลังมองหา'}<span>{filtered.length} รายการ</span></h2></div><div className="result-tools"><select aria-label="เรียงลำดับ" value={f.sort} onChange={e=>change('sort',e.target.value)}><option value="newest">ใหม่ที่สุดก่อน</option><option value="oldest">เก่าที่สุดก่อน</option><option value="title">ชื่อประกาศ ก–ฮ</option></select><div className="view-toggle"><button aria-label="มุมมองรายการ" className={view==='list'?'on':''} onClick={()=>setView('list')}><List size={17}/></button><button aria-label="มุมมองตาราง" className={view==='grid'?'on':''} onClick={()=>setView('grid')}><LayoutGrid size={16}/></button></div></div></div>
 <div className="month-loader">{STATIC&&<><label>ปีประกาศ (พ.ศ.) <select aria-label="ปีประกาศ (พ.ศ.)" disabled={loading} value={selectedYear} onChange={e=>{const year=e.target.value;setSelectedYear(year);setAllMonths(true);const nextMonth=year+'-01';setMonth(nextMonth);setF(p=>({...p,from:'',to:''}));connect('',true,nextMonth,true,year)}}>{(dataInfo?.availableYears||[selectedYear]).map(year=><option key={year} value={year}>{Number(year)+543} ({year})</option>)}</select></label><label><input type="checkbox" checked={allMonths} disabled={loading} onChange={e=>{setAllMonths(e.target.checked);connect('',true,month,e.target.checked)}}/> ทุกเดือนในปีที่เลือก</label></>}<label>เดือน (ค.ศ.) <input aria-label="เดือนของฐานข้อมูล (ค.ศ.)" type="month" disabled={loading||(STATIC&&allMonths)} value={month} onChange={e=>{setMonth(e.target.value);if(e.target.value)setSelectedYear(e.target.value.slice(0,4))}} min={dataInfo?.availableMonths?.[0]?.month||'1885-01'} max={new Date().toISOString().slice(0,7)}/></label><button disabled={loading||!month} onClick={()=>connect('',true,month)}><RefreshCw size={13} className={loading?'spin':''}/> {loading?'กำลังเชื่อมต่อ…':'โหลด / รีเฟรช'}</button></div>
 {STATIC&&<p className="history-hint">เลือกปีเพื่อโหลดข้อมูลย้อนหลัง • หากระบุวันที่ข้ามปี ให้กด “ค้นหาประกาศ” เพื่อโหลดทุกเดือนในช่วงนั้น • ปีเก่าค้นชื่อประกาศได้ ส่วน OCR นำเข้าเฉพาะสองปีล่าสุด</p>}

 <div className={'dataset-banner '+(dataInfo?.complete&&!connectionError?'live':'')}><Info size={15}/><span>{dataInfo?`ข้อมูลจริง ${dataInfo.month} • ${rows.length} ประกาศ • ${dataInfo.complete?(STATIC?'ครบไฟล์เดือนที่นำเข้า • ซิงก์ผ่าน GitHub Actions':'คัดกรองครบไฟล์รายเดือน'):'สำเนาบางส่วน ไม่ครบเดือน'}${connectionError?(STATIC?' • โปรดตรวจเวลา sync':' • เชื่อมต่อสดไม่ได้'):''} • OCR ${rows.filter(r=>r.text).length} ฉบับ`:'กำลังเตรียมข้อมูลจริง ไม่มีข้อมูลจำลอง'}</span>{dataInfo&&<a href={dataInfo.source} target="_blank" rel="noreferrer">ไฟล์ต้นทาง <ExternalLink size={12}/></a>}</div>

 {(f.q||filterCount>0)&&<div className="active-filters">{f.q&&<button onClick={()=>{change('q','');setInput('')}}>คำค้น: {f.q}<X size={12}/></button>}{f.sub&&<button onClick={()=>change('sub','')}>{f.sub}<X size={12}/></button>}{(f.from||f.to)&&<button onClick={()=>setF(p=>({...p,from:'',to:''}))}>{f.from?dateTH(f.from):'เริ่มต้น'} – {f.to?dateTH(f.to):'ปัจจุบัน'}<X size={12}/></button>}<button onClick={reset}>ล้างตัวกรอง</button></div>}
 <div className={'result-list '+(view==='grid'?'grid':'')} aria-busy={loading}>{visible.map((r,i)=><article className="result-card" key={r.id} style={{animationDelay:`${i*55}ms`}}><div className={'document-icon '+(r.group==='nacc'?'lavender':'')}><FileText size={23}/><span>ประกาศ</span></div><div className="card-content"><div className="card-tags"><span className={'tag '+(r.group==='nacc'?'purple':'')}>{r.group==='nacc'?'ป.ป.ช.':'แต่งตั้งบุคลากร'}</span><span className="sub-tag">{r.sub}</span>{r.text&&<span className="ocr-tag"><span/> ค้นเนื้อหาได้</span>}</div><button className="document-title" onClick={()=>setSelected(r)}>{highlight(r.title)}</button><div className="card-meta"><span><CalendarDays size={13}/>{dateTH(r.date)}</span><span className="meta-divider">·</span><span>เล่ม {r.volume||'–'} ตอน {r.part||'–'}</span><span className="meta-divider">·</span><span>{r.issuer||'ไม่ระบุหน่วยงาน'}</span></div>{f.q&&f.scope!=='title'&&r.text.includes(f.q)&&<p className="snippet">…{highlight(r.text.slice(Math.max(0,r.text.indexOf(f.q)-30),r.text.indexOf(f.q)+110))}…</p>}<div className="card-bottom"><button onClick={()=>setSelected(r)}>อ่านประกาศ <ArrowUpRight size={14}/></button><span>Open Law Data Thailand</span></div></div><button className={'bookmark icon-button '+(saved.includes(r.id)?'is-saved':'')} aria-label={saved.includes(r.id)?'เลิกบันทึก':'บันทึกประกาศ'} onClick={()=>toggleSaved(r)}><Bookmark size={18} fill={saved.includes(r.id)?'currentColor':'none'}/></button></article>)}</div>
 {!filtered.length&&<div className="empty"><BookOpen size={40}/><h3>{loading?'กำลังโหลดประกาศจริง…':'ไม่พบในข้อมูลที่โหลดแล้ว'}</h3><p>ลองเปลี่ยนคำค้นหรือเดือนข้อมูล • ผลว่างไม่ได้หมายความว่าไม่มีประกาศในฐานทั้งหมด</p><button className="primary" onClick={reset}>ล้างตัวกรองและลองใหม่</button></div>}
 <Pagination page={safePage} pages={pages} total={filtered.length} pageSize={pageSize} onPage={n=>{setPage(n);document.querySelector('.results-heading')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}} onSize={n=>{setPageSize(n);setPage(1)}} notify={notify}/>
 <div className="results-footnote"><ShieldCheck size={14}/> เพื่อความถูกต้องทางกฎหมาย โปรดตรวจสอบประกาศฉบับจริงในราชกิจจานุเบกษา</div></div></section>
 <section className="bottom-callout"><div className="callout-icon"><BookOpen size={28}/><span>✧</span></div><div><h3>เรื่องสำคัญ ไม่ควรเป็นเรื่องหายาก</h3><p>ทำให้ข้อมูลสาธารณะ เป็นข้อมูลที่ทุกคนเข้าถึงได้จริง</p></div><button onClick={()=>{window.scrollTo({top:230,behavior:'smooth'});document.querySelector('.search-main input').focus()}}>เริ่มค้นหาประกาศ <ArrowUpRight size={17}/></button></section></main>
 <footer><a className="footer-brand" href="#"><Library size={20}/> ราชค้น</a><span>ข้อมูลโดย <a href={DATASET} target="_blank" rel="noreferrer">Open Law Data Thailand ↗</a> · CC BY 4.0</span><span>ออกแบบเพื่อการเข้าถึง ไม่ใช่คำปรึกษาทางกฎหมาย</span></footer>
 <div className="toast-stack" aria-live="polite">{toasts.map(t=><div className={'toast '+t.type} key={t.id}>{t.type==='error'?<AlertCircle size={19}/>:t.type==='loading'?<LoaderCircle className="spin" size={19}/>:<CheckCircle2 size={19}/>}<span>{t.text}</span><button aria-label="ปิดการแจ้งเตือน" onClick={()=>setToasts(p=>p.filter(x=>x.id!==t.id))}><X size={15}/></button></div>)}</div>
 {(selected||help)&&<div className="modal-backdrop" onClick={()=>{setSelected(null);setHelp(false)}}><section role="dialog" aria-modal="true" aria-label={help?'เกี่ยวกับข้อมูล':'รายละเอียดประกาศ'} className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" autoFocus aria-label="ปิด" onClick={()=>{setSelected(null);setHelp(false)}}><X/></button>{help?<><div className="modal-symbol"><Database/></div><h2>ข้อมูลเปิด เพื่อการค้นพบ</h2><p>ราชค้นช่วยค้นประกาศแต่งตั้งและประกาศเกี่ยวกับสำนักงานและคณะกรรมการ ป.ป.ช. จากชุดข้อมูล soc-ratchakitcha ของ Open Law Data Thailand ภายใต้สัญญาอนุญาต CC BY 4.0</p><h3>GitHub Pages และข้อมูลจริง</h3><p>เวอร์ชัน Pages ใช้ GitHub Actions ดาวน์โหลด metadata และ OCR จาก Hugging Face มาจัดเก็บพร้อมเว็บ ไม่เรียก API ของ Node บน Pages ปุ่มรีเฟรชโหลดชุดข้อมูลที่เผยแพร่ล่าสุด ไม่ใช่สั่งงาน Actions นำเข้าข้อมูลชื่อประกาศจากทุกปีที่ต้นทางมีให้ เลือกปี พ.ศ. เพื่อโหลดปีนั้น หรือระบุช่วงวันข้ามปีแล้วกดค้นหา เนื้อหา OCR นำเข้าเฉพาะปีปัจจุบันและปีก่อนหน้า การค้นชื่อและเนื้อหาทำงานกับเดือนที่โหลดแล้ว ดูเวลาซิงก์ต้นทางได้ที่สถานะฐานข้อมูล</p><h3>ค้นหาได้ลึกแค่ไหน?</h3><p>โหลด metadata จากไฟล์ JSONL รายเดือนโดยตรง แล้วคัดเฉพาะประกาศแต่งตั้งและ ป.ป.ช. ตัวกรองและการเรียงลำดับทำงานกับเดือนที่โหลด ไม่ใช่ฐานทุกปี หากเชื่อมต่อสดไม่ได้จะแสดงสำเนาข้อมูลจริงที่นำเข้าไว้ พร้อมระบุว่าครบเดือนหรือเป็นบางส่วน การแบ่งหมวดย่อยใช้คำสำคัญจึงอาจคลาดเคลื่อนได้ การค้นเนื้อหาจะเรียกบริการ OCR แยก (สูงสุด 100 ผล) และใช้เฉพาะข้อความที่จับคู่กับประกาศที่แสดงได้</p><h3>ความสดใหม่และความถูกต้อง</h3><p>ปุ่มรีเฟรชดาวน์โหลดไฟล์เดือนที่เลือกจากต้นทางใหม่ หากเซิร์ฟเวอร์เชื่อมต่อไม่ได้จะลองผ่านเบราว์เซอร์โดยตรง และคงสำเนาข้อมูลจริงไว้เมื่อทั้งสองช่องทางล้มเหลว เวลาการเชื่อมต่อสดแยกจากวันที่นำเข้าสำเนา เซิร์ฟเวอร์ลองซิงก์เดือนปัจจุบันทุก 24 ชั่วโมงขณะเปิดทำงาน ข้อมูล metadata ไม่มีข้อความ OCR ในตัว ควรตรวจสอบ PDF ต้นฉบับเสมอ</p><a className="primary" href={DATASET} target="_blank" rel="noreferrer">ไปยังฐานข้อมูลต้นทาง <ExternalLink size={16}/></a></>:<><span className="tag">{selected.sub}</span><h2>{selected.title}</h2><p className="modal-date"><CalendarDays size={15}/>{dateTH(selected.date)} · เล่ม {selected.volume} ตอน {selected.part}</p><div className="ocr-notice"><Info size={16}/> {selected.text?'ข้อความ OCR อาจคลาดเคลื่อน โปรดตรวจสอบเอกสารต้นฉบับ':'ข้อมูลชื่อประกาศและลิงก์จากฐานจริง • ยังไม่ได้โหลด OCR'}</div><div className="document-text">{selected.text?highlight(selected.text):'ยังไม่มีข้อความ OCR ในข้อมูลที่โหลด โปรดเปิด PDF ต้นฉบับด้านล่าง'}</div><div className="modal-actions"><button onClick={()=>toggleSaved(selected)}><Bookmark size={16}/>{saved.includes(selected.id)?'บันทึกแล้ว':'บันทึกประกาศ'}</button>{selected.pdf?<a className="primary" href={selected.pdf} target="_blank" rel="noreferrer">เปิดต้นฉบับ PDF <ExternalLink size={15}/></a>:<a href={DATASET} target="_blank" rel="noreferrer">ไม่พบ URL PDF • ไปที่ฐานข้อมูล <ExternalLink size={14}/></a>}</div></>}</section></div>}
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);
